name: Playwright MCP Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4
    # Set up Node.js environment
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    # Install Playwright browsers and dependencies
    - name: Install Playwright
      run: npx playwright install --with-deps
    # Install Playwright MCP server
    - name: Install Playwright MCP Server
      run: npm install @playwright/mcp@latest
    
    # Start Playwright MCP server in the background
    - name: Start Playwright MCP Server
      run: npm run mcp:headless
      # env:
      #   PLAYWRIGHT_WS_ENDPOINT: ws://localhost:8931/
    
    # # Wait for MCP server to be ready (optional, to ensure server is up)
    # - name: Wait for MCP Server
    #   run: sleep 10
    
    # # Run Playwright tests
    # - name: Run Playwright Tests
    #   run: npx playwright test
    #   env:
    #     PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
    
    # Upload test artifacts (e.g., screenshots, logs) if tests fail
    - name: Upload Test Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-artifacts
        path: playwright-report/
   
    # Generate and serve HTML report
    - name: Generate Playwright Report
      if: ${{ always() }}
      run: npx playwright show-report playwright-report
