name: Playwright MCP Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Checkout:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
  InstallDependency:
    needs: Checkout
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
  PlaywrightInstallation:
    needs: InstallDependency
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
  MCPServerInstallation:
    needs: PlaywrightInstallation
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright MCP Server
        run: npm install @playwright/mcp@latest
  TestExecution:
    needs: MCPServerInstallation
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Install Playwright MCP Server
        run: npm install @playwright/mcp@latest
      - name: Start Playwright MCP Server
        run: npm run mcp:headless &
      - name: Wait for MCP Server
        run: sleep 10
      - name: Run Playwright Tests
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
  UploadTestArtifacts:
    needs: TestExecution
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout the окна repository code
        uses: actions/checkout@v4
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts
          path: cucumber-report.html
