name: Playwright MCP Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CheckoutCode:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4
    # Set up Node.js environment
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    # Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Install Playwright browsers and dependencies
    - name: Install Playwright
      run: npx playwright install --with-deps
    # Install Playwright MCP server
    - name: Install Playwright MCP Server
      run: npm install @playwright/mcp@latest
    # Install and run
    - name: Start Playwright MCP Server
      run: npm run mcp:headless

  UploadTestArtifacts:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: InstallPlaywrightAndMCPServer  # This job depends on InstallPlaywrightAndMCPServer job
    steps:
    # Upload test artifacts (e.g., screenshots, logs) if tests fail
    - name: Upload Test Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-artifacts
        path: cucumber-report.html
