name: Playwright MCP Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CheckoutCode:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

  InstallDependency:
    needs: CheckoutCode
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the code again since jobs are isolated
      - uses: actions/checkout@v4
      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependencies
      - name: Install Dependencies
        run: npm ci

  PlaywrightInstallation:
    needs: InstallDependency
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      # Install Playwright browsers and dependencies
      - name: Install Playwright
        run: npx playwright install --with-deps

  MCPServerInstallation:
    needs: PlaywrightInstallation
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      # Install Playwright MCP Server
      - name: Install Playwright MCP Server
        run: npm install @playwright/mcp@latest

  TestExecution:
    needs: MCPServerInstallation
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependencies
      - name: Install Dependencies
        run: npm ci
      # Install Playwright browsers and dependencies
      - name: Install Playwright
        run: npx playwright install --with-deps
      # Install Playwright MCP Server
      - name: Install Playwright MCP Server
        run: npm install @playwright/mcp@latest
      # Start Playwright MCP Server in the background
      - name: Start Playwright MCP Server
        run: npm run mcp:headless &
      # Wait briefly to ensure the server starts (adjust as needed)
      - name: Wait for MCP Server
        run: sleep 10
      # Run Playwright tests (assuming this generates cucumber-report.html)
      - name: Run Playwright Tests
        run: npx playwright test

  UploadTestArtifacts:
    needs: TestExecution
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Ensure this job runs even if TestExecution fails
    if: ${{ always() }}
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Set up Node.js environment (if report generation needs it)
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependencies (if required for report access)
      - name: Install Dependencies
        run: npm ci
      # Upload test artifacts (e.g., cucumber-report.html)
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts
          path: cucumber-report.html
